"""empty message

Revision ID: dd13f3c7a72c
Revises: dcf92e62597c
Create Date: 2021-04-17 10:07:46.502670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd13f3c7a72c'
down_revision = 'dcf92e62597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_timestamp', table_name='notification')
    op.drop_column('notification', 'timestamp')
    op.drop_column('user', 'last_notification_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_notification_read_time', sa.DATETIME(), nullable=True))
    op.add_column('notification', sa.Column('timestamp', sa.FLOAT(), nullable=True))
    op.create_index('ix_notification_timestamp', 'notification', ['timestamp'], unique=False)
    # ### end Alembic commands ###
